declare const _exports: {
    API: typeof KsWc;
    Cls: typeof KsWc;
    KsWc: typeof KsWc;
    KsRest: typeof KsRest;
    KsCs: typeof KsCs;
    driver: typeof KsCs;
    default: KsCs;
    config: {};
    set(payload?: KsWc.KsOption): KsWc;
    "__#1@#cloneObj"(obj: any): any;
    build(opt?: KsWc.KsOption): any;
    get(query?: KsWc.TList<any>): any;
    list(query?: KsWc.TList<any>): any;
    add(payload: string | KsWc.TList<any>): any;
    insert(payload: string | KsWc.TList<any>): any;
    update(payload: string | KsWc.TList<any>, id?: string | number, query?: string | KsWc.TList<any>): any;
    delete(id: string | number, query?: KsWc.TList<any>): any;
    select(id: string | number, query?: KsWc.TList<any>): any;
    query(payload: ReqConfig): any;
    request(payload: ReqConfig): any;
    connect(opt?: KsWc.TList<any>): any;
};
export = _exports;
import KsWc = require("./src/KsWc");
import KsRest = require("./src/KsRest");
import KsCs = require("./src/KsCs");
